In [ ]:
#EJERCIO 1
import pandas as pd
print(pd.__version__)
id_empleado=pd.read_csv("C:/Users/Usuario/documents/data-science/01-pyton-intro/empleados.csv")
id_empleado.head(n=10)

3.0.5

,id_empleado,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
0,1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1,1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
2,1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
3,1004,Laura Gomez,Marketing,Sevilla,24900.0,2023-05-21,3.0
4,1005,Paula Torres,RRHH,Madrid,54800.0,2019-01-18,5.0
5,1006,Lucia Mora,Finanzas,Valencia,49200.0,2022-03-25,3.0
6,1007,Javier Nieto,IT,Valencia,44400.0,2015-04-20,NaN
7,1008,Sergio Leon,Operaciones,Barcelona,28600.0,2020-07-01,2.0
8,1009,Lucia Nieto,Operaciones,Madrid,39700.0,2015-06-20,1.0
9,1010,Laura Lara,Finanzas,Sevilla,32800.0,2022-02-20,5.0

In [5]:
#EJERCIO 2
nombre_depa_salario=id_empleado[['nombre','departamento','salario']]
nombre_depa_salario

          nombre departamento  salario
0     Marta Ruiz     Finanzas  44300.0
1     Elena Sanz         RRHH  22000.0
2     Ana Prieto       Ventas  58200.0
3    Laura Gomez    Marketing  24900.0
4   Paula Torres         RRHH  54800.0
..           ...          ...      ...
85  Nuria Torres  Operaciones  29700.0
86    Diego Sanz         RRHH  36200.0
87  Lucia Prieto  Operaciones  28500.0
88  Sergio Gomez         RRHH  51600.0
89     Ana Gomez    Marketing  41400.0

[90 rows x 3 columns]

In [8]:
#EJERCICIO 3
filas_selecionadas=id_empleado[id_empleado['id_empleado'].isin([1003,1007,1015])]
filas_selecionadas

,id_empleado,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
2,1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
6,1007,Javier Nieto,IT,Valencia,44400.0,2015-04-20,NaN
14,1015,Sofia Mora,IT,Madrid,37100.0,2024-10-18,3.0

In [13]:
#EJERCICIO 4 
id_empleado.iloc[0:10,0:3]

   id_empleado        nombre departamento
0         1001    Marta Ruiz     Finanzas
1         1002    Elena Sanz         RRHH
2         1003    Ana Prieto       Ventas
3         1004   Laura Gomez    Marketing
4         1005  Paula Torres         RRHH
5         1006    Lucia Mora     Finanzas
6         1007  Javier Nieto           IT
7         1008   Sergio Leon  Operaciones
8         1009   Lucia Nieto  Operaciones
9         1010    Laura Lara     Finanzas

In [30]:
#EJERCICIO 5
por_salario=id_empleado.sort_values("salario", ascending=False)
por_salario.head(n=5)

,id_empleado,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
31,1032,Diego Gomez,Marketing,Madrid,59500.0,2023-07-14,5.0
52,1053,Laura Torres,IT,Barcelona,59400.0,2016-03-30,1.0
2,1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
45,1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
61,1062,Diego Prieto,RRHH,Madrid,55600.0,2015-01-06,1.0

In [35]:
#EJERCICIO 6

departamento_ordenado=id_empleado.sort_values("departamento").sort_values("salario",ascending=False)
departamento_ordenado

,id_empleado,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
31,1032,Diego Gomez,Marketing,Madrid,59500.0,2023-07-14,5.0
52,1053,Laura Torres,IT,Barcelona,59400.0,2016-03-30,1.0
2,1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
45,1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
61,1062,Diego Prieto,RRHH,Madrid,55600.0,2015-01-06,1.0
...,...,...,...,...,...,...,...
81,1082,Sergio Sanz,Marketing,Madrid,22000.0,2017-09-14,2.0
1,1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
42,1043,Javier Prieto,Operaciones,Barcelona,22000.0,2021-09-27,1.0
47,1048,Sofia Ferrer,Ventas,Barcelona,22000.0,2017-09-16,2.0
19,1020,Javier Sanz,Ventas,Madrid,22000.0,2018-02-15,5.0