In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [2]:
ventas=pd.read_csv("C:/Users/Usuario/Documents/data-science/01-pyton-intro/ventas.csv")
ventas.head(n=10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [3]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [6]:
ventas[ventas["vendedor"].isna()|ventas["descuento"].isna()]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
33,2024-01-11,Sur,Javier Sanz,Laptop Pro,Tecnologia,5,1200,NaN
72,2024-01-25,Oeste,Ana Torres,Teclado Mec,Accesorios,12,95,NaN
78,2024-01-28,Sur,Pedro Diaz,Tablet Air,Tecnologia,3,640,NaN
79,2024-01-29,Oeste,NaN,Raton Ergo,Accesorios,14,45,0.10
82,2024-01-30,Oeste,Pedro Diaz,Laptop Pro,Tecnologia,7,1200,NaN
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320,NaN
102,2024-02-03,Norte,Ana Torres,Raton Ergo,Accesorios,11,45,NaN
109,2024-02-04,Este,Ana Torres,Raton Ergo,Accesorios,12,45,NaN
123,2024-02-09,Este,Sofia Leon,Silla Ergo,Mobiliario,14,280,NaN
135,2024-02-13,Este,Marta Ruiz,Laptop Pro,Tecnologia,8,1200,NaN
161,2024-02-18,Oeste,NaN,Silla Ergo,Mobiliario,1,280,0.05
203,2024-02-28,Norte,NaN,Raton Ergo,Accesorios,4,45,0.10
222,2024-03-04,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200,NaN
224,2024-03-05,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,NaN
239,2024-03-11,Este,Javier Sanz,Escritorio,Mobiliario,3,450,NaN
271,2024-03-26,Sur,Javier Sanz,Silla Ergo,Mobiliario,11,280,NaN
283,2024-03-28,Este,Javier Sanz,Tablet Air,Tecnologia,2,640,NaN
310,2024-04-08,Oeste,Sofia Leon,Laptop Pro,Tecnologia,10,1200,NaN
405,2024-05-05,Norte,Carlos Vega,Escritorio,Mobiliario,9,450,NaN
424,2024-05-14,Centro,Sofia Leon,Monitor 27,Tecnologia,9,320,NaN
456,2024-05-28,Oeste,NaN,Tablet Air,Tecnologia,5,640,0.00
530,2024-06-16,Este,Ana Torres,Teclado Mec,Accesorios,9,95,NaN
535,2024-06-17,Este,Luis Gomez,Escritorio,Mobiliario,1,450,NaN
549,2024-06-20,Oeste,NaN,Raton Ergo,Accesorios,14,45,0.10
553,2024-06-22,Norte,NaN,Raton Ergo,Accesorios,7,45,0.05
571,2024-06-28,Este,NaN,Laptop Pro,Tecnologia,13,1200,0.00
577,2024-06-29,Este,NaN,Tablet Air,Tecnologia,8,640,0.00
635,2024-07-14,Centro,Pedro Diaz,Monitor 27,Tecnologia,5,320,NaN
639,2024-07-16,Norte,NaN,Raton Ergo,Accesorios,5,45,0.10
660,2024-07-21,Sur,NaN,Monitor 27,Tecnologia,14,320,0.00
668,2024-07-23,Sur,Javier Sanz,Auriculares,Accesorios,6,130,NaN
678,2024-07-27,Norte,Marta Ruiz,Laptop Pro,Tecnologia,3,1200,NaN
720,2024-08-09,Norte,Elena Mora,Teclado Mec,Accesorios,8,95,NaN
746,2024-08-18,Centro,NaN,Escritorio,Mobiliario,13,450,0.15
758,2024-08-20,Centro,NaN,Silla Ergo,Mobiliario,14,280,0.00
781,2024-08-28,Norte,NaN,Laptop Pro,Tecnologia,5,1200,0.00
795,2024-09-01,Oeste,Ana Torres,Silla Ergo,Mobiliario,6,280,NaN
803,2024-09-04,Sur,Ana Torres,Auriculares,Accesorios,5,130,NaN
814,2024-09-07,Este,Marta Ruiz,Escritorio,Mobiliario,6,450,NaN
830,2024-09-13,Sur,Javier Sanz,Monitor 27,Tecnologia,9,320,NaN
876,2024-09-26,Norte,Carlos Vega,Escritorio,Mobiliario,2,450,NaN
881,2024-09-27,Norte,Marta Ruiz,Silla Ergo,Mobiliario,7,280,NaN
884,2024-09-27,Este,Marta Ruiz,Escritorio,Mobiliario,7,450,NaN
904,2024-10-05,Sur,Ana Torres,Tablet Air,Tecnologia,6,640,NaN
935,2024-10-12,Sur,NaN,Laptop Pro,Tecnologia,8,1200,0.15
942,2024-10-14,Este,Pedro Diaz,Teclado Mec,Accesorios,2,95,NaN
958,2024-10-18,Oeste,NaN,Monitor 27,Tecnologia,13,320,0.15
991,2024-10-29,Sur,NaN,Silla Ergo,Mobiliario,1,280,NaN
1032,2024-11-07,Oeste,NaN,Raton Ergo,Accesorios,9,45,0.00
1076,2024-11-24,Sur,Sofia Leon,Tablet Air,Tecnologia,7,640,NaN
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200,0.00
1184,2024-12-27,Oeste,Luis Gomez,Escritorio,Mobiliario,10,450,NaN

In [8]:
ventas_sin_nulos=ventas.dropna()
ventas_sin_nulos

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [10]:
ventas_sinnulos_columna=ventas.dropna(subset="vendedor")
ventas_sinnulos_columna

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [11]:
ventas.dropna(axis=1)

           fecha  region     producto   categoria  unidades  precio_unitario
0     2024-01-02   Oeste  Auriculares  Accesorios         5              130
1     2024-01-02     Sur   Monitor 27  Tecnologia        14              320
2     2024-01-02  Centro   Silla Ergo  Mobiliario         1              280
3     2024-01-02  Centro   Laptop Pro  Tecnologia        10             1200
4     2024-01-03     Sur  Auriculares  Accesorios         2              130
...          ...     ...          ...         ...       ...              ...
1195  2024-12-30    Este   Raton Ergo  Accesorios         4               45
1196  2024-12-30    Este   Laptop Pro  Tecnologia        13             1200
1197  2024-12-31   Oeste   Monitor 27  Tecnologia         2              320
1198  2024-12-31   Norte   Monitor 27  Tecnologia         6              320
1199  2024-12-31   Norte   Raton Ergo  Accesorios         8               45

[1200 rows x 6 columns]