In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [5]:
df=pd.read_csv("C:/Users/Usuario/Documents/data-science/01-pyton-intro/ventas.csv")
df.head(n=10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [3]:
df.tail(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200,0.10
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10
1193,2024-12-30,Centro,Ana Torres,Raton Ergo,Accesorios,7,45,0.00
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.00
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [6]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [7]:
df.sample(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
144,2024-02-14,Oeste,Sofia Leon,Laptop Pro,Tecnologia,10,1200,0.0
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
727,2024-08-12,Sur,Sofia Leon,Raton Ergo,Accesorios,5,45,0.0
1150,2024-12-16,Centro,Pedro Diaz,Auriculares,Accesorios,12,130,0.0
453,2024-05-27,Norte,Ana Torres,Laptop Pro,Tecnologia,11,1200,0.0
61,2024-01-20,Oeste,Sofia Leon,Auriculares,Accesorios,13,130,0.1
47,2024-01-16,Oeste,Carlos Vega,Raton Ergo,Accesorios,7,45,0.0
894,2024-10-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,10,280,0.0
934,2024-10-12,Oeste,Sofia Leon,Teclado Mec,Accesorios,9,95,0.0
734,2024-08-13,Centro,Carlos Vega,Monitor 27,Tecnologia,1,320,0.0

In [8]:
df.describe(include="object")

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10360\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

             fecha region    vendedor    producto   categoria
count         1200   1200        1182        1200        1200
unique         349      5           8           8           3
top     2024-02-21  Norte  Marta Ruiz  Silla Ergo  Tecnologia
freq             9    305         170         177         447

In [9]:
df["region"].unique()

<StringArray>
['Oeste', 'Sur', 'Centro', 'Norte', 'Este']
Length: 5, dtype: str

In [10]:
df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [ ]:
#seleccionar columnas

In [11]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [13]:
df[["fecha", "region"]]

           fecha  region
0     2024-01-02   Oeste
1     2024-01-02     Sur
2     2024-01-02  Centro
3     2024-01-02  Centro
4     2024-01-03     Sur
...          ...     ...
1195  2024-12-30    Este
1196  2024-12-30    Este
1197  2024-12-31   Oeste
1198  2024-12-31   Norte
1199  2024-12-31   Norte

[1200 rows x 2 columns]

In [14]:
df.loc[0]

fecha               2024-01-02
region                   Oeste
vendedor            Pedro Diaz
producto           Auriculares
categoria           Accesorios
unidades                     5
precio_unitario            130
descuento                  0.0
Name: 0, dtype: object

In [17]:
df.loc[0: 2, ["producto","unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [18]:
df.loc[:, ["producto","unidades"]]

         producto  unidades
0     Auriculares         5
1      Monitor 27        14
2      Silla Ergo         1
3      Laptop Pro        10
4     Auriculares         2
...           ...       ...
1195   Raton Ergo         4
1196   Laptop Pro        13
1197   Monitor 27         2
1198   Monitor 27         6
1199   Raton Ergo         8

[1200 rows x 2 columns]

In [19]:
df.iloc[-5:, 3:6]

        producto   categoria  unidades
1195  Raton Ergo  Accesorios         4
1196  Laptop Pro  Tecnologia        13
1197  Monitor 27  Tecnologia         2
1198  Monitor 27  Tecnologia         6
1199  Raton Ergo  Accesorios         8